### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by tommyd3mdi** [qoomon/Jira-Issue-Card-Printer#13]
For the more sensible folks you should mention that the bookmarklet contacts Google Analytics and sends certain events regarding the usage of the bookmarklet's print overlay or possible Javascript exceptions to their service.

**Comment by qoomon** [comment]
I will replace GA with a simple custom  logging solution this week

**Comment by qoomon** [comment]
Any recommendations how I should do so

**Comment by tommyd3mdi** [comment]
Add it to the README file, place a note on your blog entry, etc. It is just so that possibly sensible data from a private JIRA instance might be sent out to Analytics and people do not know it.

**Comment by qoomon** [comment]
do you may know an alternative to GA i just need to know how many people
use my bookmarklet.

**Comment by tommyd3mdi** [comment]
There are alternatives, of course, for example [Piwik](http://piwik.org/), but the issue is not that the analytics are sent out to Google, but that there is an analytics functionality at all. I understand that you want feedback and this wish is viable, _if_ you actually mention it prominently.

**Comment by qoomon** [comment]
I just add a eye-catching note on my About page http://qoomon.blogspot.de/2014/01/jira-issue-card-printer-bookmarklet.html
