### ISSUE TITLE
Size is too big.

### ISSUE THREAD

**Issue by houmie** [qoomon/Jira-Issue-Card-Printer#15]
This is really useful. Thank you for the plugin.

One problem I see is the size of the cards. They take too much space. Is there a way to resize them?

**Comment by qoomon** [comment]
What format do you need?

Maybe the Attachment feature is helpful to you. 
Just write  **\*Attachment*\** into description of an issue and below this marker no text is printed anymore. Furthermore an paper-clip icon is attached to the printed card.

Kind Regards

**Comment by houmie** [comment]
Problem is that we have like 50 card for a team of 6.  Each card fits on one A4 page. It takes too much space. I wished there was a way to make them much smaller with just the title perhaps.

**Comment by qoomon** [comment]
What format would suit you?
Print just the header wouldn't be a problem. i will add an toggle for that.
One Issue per page is okay for you?

**Comment by houmie** [comment]
Thank you. That would be amazing having a toggle to show only the reduced sized tickets.
It would make sense to reduce the size of the tickets to fit six tickets on a landscape A4 page.

**Comment by qoomon** [comment]
Okay i'll try some options at weekend. 
So long

**Comment by qoomon** [comment]
done!  hope it will help you.
