### ISSUE TITLE
Variable/Custom Sizing

### ISSUE THREAD

**Issue by crankietech** [qoomon/Jira-Issue-Card-Printer#16]
I find that if I'm trying to print this out on an A3 piece of paper, I get full-width tickets (i.e. 7.5") regardless of what I instruct the printer to print.  Would having a fixed size option as well solve this?

**Comment by qoomon** [comment]
i am working on this right now.
i will add an option to print an grid of cards, you will be able to set column and row count.
i think will release it on early June.

regards
bengt

**Comment by crankietech** [comment]
By the way, this is a fantastic tool.

**Comment by crankietech** [comment]
Speaking of fantastic tools, I just close this ticket by accident ;)

**Comment by qoomon** [comment]
:-D

**Comment by qoomon** [comment]
Develop Version is running exept the auto scaling. Probably I will finish this week.

**Comment by qoomon** [comment]
should be fixed with last commit

**Comment by crankietech** [comment]
Works great.  Thanks!
