### ISSUE TITLE
Reflect Status of Ticket

### ISSUE THREAD

**Issue by crankietech** [qoomon/Jira-Issue-Card-Printer#19]
Would it be possible to somehow reflect the status of the ticket?  Such as Closed, Resolved, In Progress, Open, etc. (this should possibly be optional, since if you're printing them for a board, you're going to be moving them across status columns anyway)

**Comment by qoomon** [comment]
this is no problem. may you have an idea where i should place it :-D
this is the current full feature layout  -> https://jsfiddle.net/qoomon/ykbLb2pw/
