### ISSUE TITLE
when projet name/ code is "long", ID is truncated

### ISSUE THREAD

**Issue by Moosh-be** [qoomon/Jira-Issue-Card-Printer#20]
![capture du 2015-07-06 11 38 40](https://cloud.githubusercontent.com/assets/388085/8519569/d5f4f192-23d3-11e5-98aa-c56c0d728eb7.png)

**Comment by qoomon** [comment]
how many signs do you need?

**Comment by qoomon** [comment]
I just maximize the id field width. 62676efed4e24cebf73ed81677cde10ed1e63737

**Comment by qoomon** [comment]
And i change the test direction to right so ne number schould always be visible

**Comment by Moosh-be** [comment]
very great
 thank you

**Comment by qoomon** [comment]
you're welcome
