### ISSUE TITLE
Custom Font Size for Issue Summary

### ISSUE THREAD

**Issue by TNikoletta** [qoomon/Jira-Issue-Card-Printer#21]
It would be greatly appreciated if you could implement font size option. I like to print relatively small cards for physical board (4 row and 3 column in A4 paper). With this setting, the card title can only be read when standing very close to the board. 
Thank you!

**Comment by qoomon** [comment]
Which size do you mean?
I could easily add an option to scale the size of the summary and description.
But i cant make the id scalable that easy.
Would this be sufficient for you?

**Comment by TNikoletta** [comment]
The summary would be great. Thank you. 
It would be nice to have this option for the ID too, but I understand if it requires too much work.

**Comment by BaSche** [comment]
Probably summary and description shouldn't be scaled when you print the issues in rows or columns (eg 2x2 or 3x3). We usually print Stories 2x2 and Tasks 3x3 but it gets really tiny...

**Comment by qoomon** [comment]
current version 4.2.0 should have a much better scaling behaviour.

**Comment by qoomon** [comment]
i add a scale option
