### ISSUE TITLE
Use JQL search results as selection

### ISSUE THREAD

**Issue by data219** [qoomon/Jira-Issue-Card-Printer#22]
Currently the bookmarklet does not work on the search results page. Would be very nice to use that as selection. Currently it is quite a hassle to print all issues (including subtasks) from a sprint since in the backlog one can only select regular issues (no subtasks) and within the active sprint one can not select multiple issues

**Comment by qoomon** [comment]
Currently i am in vacation. But i will look a this problem afterwards. Probably at the end of October .

**Comment by qoomon** [comment]
should work now
