### ISSUE TITLE
How to print all sub-tasks in Open Sprint?

### ISSUE THREAD

**Issue by BaSche** [qoomon/Jira-Issue-Card-Printer#23]
**As** a ScrumMaster
**I Want** to print all Issues and Sub-Tasks of the active sprint
**So That** all issues and and sub-tasks are visible on our physical board.

It is not possible to select subtasks of different issues in the active sprint view. There are no sub-tasks in the backlog view. The booklet does not seem to work in the IssueFilter, where i can find all sub-tasks of the current sprint.

Is there a way to achieve this?

**Comment by BaSche** [comment]
It might be related to #22 but i cant figure out, how it works :confused:.

**Comment by BaSche** [comment]
Okay eventually I found it. Reading actually helps ;).

1. Go to 'Issues' > 'Search for issues'
2. Enter the filter to find everything you need (e.g. project = ACME AND issuetype=sub-task AND Sprint in openSprints())
3. Press Enter

Now you can click the Booklet and everything is fine ;).

Thank you for this awesome tool :+1:

**Comment by qoomon** [comment]
You're welcome
