### ISSUE TITLE
Show Epic or parent issue on card

### ISSUE THREAD

**Issue by BaSche** [qoomon/Jira-Issue-Card-Printer#24]
As a guy who has to print the issues
I want to see the Epic or the parent-issue-ID on the tickets
To improve the handling on a physical board and mae it easier to group tasks to stories.

**Comment by qoomon** [comment]
This should already working. I will check it tomorrow.
Do you use JIRA or another supported issue tracke?r

**Comment by BaSche** [comment]
We are using Jira and have a lot of sub tasks to sort out. 

Thanks for the fast reply.

**Comment by thajdu1** [comment]
Epics are already visible for us for a long time. I'm not sure about the parent ticket though.

**Comment by BaSche** [comment]
Epic is working great, thx

But parent-issue is still not there.

Tested with v4.2.3

**Comment by qoomon** [comment]
what is a parent issue? is it a field of jira subtasks?
should it overwrite the epic badge?

**Comment by thajdu1** [comment]
In Jira you can create sub-tasks for a ticket that are handled in a special way and the original ticket is their parent.

**Comment by BaSche** [comment]
Overwrite the Epic would be okay, 

If I search for the JQL 'parent = KITA-2066' I find all subtasks. So I guess it is a field.

**Comment by qoomon** [comment]
okay i will have a look later today

**Comment by qoomon** [comment]
should work now
