### ISSUE TITLE
Row count does not work

### ISSUE THREAD

**Issue by thajdu1** [qoomon/Jira-Issue-Card-Printer#25]
Seems that the row count parameter is ignored and the tickets don't get scaled, I can only print two tickets per page...Was working until very recently. :)

**Comment by qoomon** [comment]
sry i will fix it

**Comment by thajdu1** [comment]
great, thanks. the tool is great btw :)

**Comment by qoomon** [comment]
is it still broken?

**Comment by thajdu1** [comment]
will check it.

**Comment by thajdu1** [comment]
seems to be the same problem still.

**Comment by qoomon** [comment]
any console output?

**Comment by qoomon** [comment]
works for me but i will revert the change tomorrow

**Comment by qoomon** [comment]
what browser do you use?

**Comment by thajdu1** [comment]
Chrome Version 46.0.2490.86 m

**Comment by qoomon** [comment]
what combination of row and column count wont work?
sry for the many questions

**Comment by thajdu1** [comment]
Screenshots: :)
![card_printer_row_count_3](https://cloud.githubusercontent.com/assets/10087580/11404551/ce3110a0-93a2-11e5-8638-cac57ebce0c2.png)
![card_printer_row_count_3_print_preview](https://cloud.githubusercontent.com/assets/10087580/11404552/ce38dfce-93a2-11e5-873e-0c26ab2ce5c5.png)

**Comment by qoomon** [comment]
Ok i can reproduce the problem. I will fix it right away.

**Comment by qoomon** [comment]
fixed with 3a14296

**Comment by thajdu1** [comment]
Great, that was super fast. :) it's working correctly now.

Thank you!
