### ISSUE TITLE
Design change

### ISSUE THREAD

**Issue by thajdu1** [qoomon/Jira-Issue-Card-Printer#26]
Hi, I'd have one more question. I've noticed that the design and the text size has changed recently.
It looked like this earlier:
![issue_card_old](https://cloud.githubusercontent.com/assets/10087580/11424463/bf06010c-944d-11e5-9d43-acce9185705f.png)
And now it looks like this:
![issue_card_new](https://cloud.githubusercontent.com/assets/10087580/11424476/c9b19760-944d-11e5-8cd5-ae4cfd7c820a.png)

Is this intentional? There's much less info visible mainly because of the bigger fonts used I think. I preferred the earlier version personally. :)

**Comment by BaSche** [comment]
It was intentionally changed by #21 

Probably there should be a parameter to use the new scaling.

**Comment by qoomon** [comment]
i will try to fix it tomorow

**Comment by thajdu1** [comment]
That would be nice, thank you. :)

**Comment by qoomon** [comment]
should be fixed

**Comment by thajdu1** [comment]
Looks great, thanks! :)
