### ISSUE TITLE
Error message: Card printer already opened

### ISSUE THREAD

**Issue by houmie** [qoomon/Jira-Issue-Card-Printer#28]
We are getting a strange error today:

At first, there is an empty popup
a second try says:

```card printer already opened!```

Thanks

**Comment by qoomon** [comment]
what issue tracker do you use?

**Comment by houmie** [comment]
I'm using JIRA

**Comment by qoomon** [comment]
I can't reproduce this error right now.
Does it occur always?

However i fixed the "Card Printer already open" Problem.
