### ISSUE TITLE
Javascript Error cardElement.css(...) is undefined

### ISSUE THREAD

**Issue by BaSche** [qoomon/Jira-Issue-Card-Printer#29]
Sorry something went wrong.

cardElement.css(...) is undefined

Please create an issue at https://github.com/qoomon/Jira-Issue-Card-Printer

scaleCards@https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:348:24
redrawCards@https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:229:5
renderCards/</<@https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:216:9

Environment
Atlassian JIRA (v6.2.1#6256-sha1:f72b283)
Firefox 43.0.1

**Comment by qoomon** [comment]
Thanks for reporting this error,
I will investigate on that later today or to tomorrow

**Comment by qoomon** [comment]
should work now, however multi cards per page is currently broken in firefox.
I'm working on it...

**Comment by BaSche** [comment]
It works again in Firefox. Thanks for looking into it :).
