### ISSUE TITLE
Mixed Content warning

### ISSUE THREAD

**Issue by chrkarow** [qoomon/Jira-Issue-Card-Printer#31]
Hi qoomon :)

When using your issue card printer a colleague of mine gets following error message in the javascript console and the output fails.

`Mixed Content: The page at ... was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint . This request has been blocked; the content must be served over HTTPS.`

It seems that the underlying JIRA is HTTPS secured but the bookmarklet tries to load content via HTTP. 
Would be really nice if you would find the time to have a look at it.

Thanks in advance.

**Comment by qoomon** [comment]
Could you provide the "insecure  endpoint",  please.

Regards

**Comment by rpelaez** [comment]
Hi @chrkarow @qoomon , are you using the JIRA plugin?

**Comment by qoomon** [comment]
we talking about the bookmarklet

**Comment by qoomon** [comment]
Based on your screenshot you provided me it looks like it's not a problem with the card printer, it is rather an issue within jira
