### ISSUE TITLE
Using Internet Explorer 11 gives "startsWith" error

### ISSUE THREAD

**Issue by Refalm** [qoomon/Jira-Issue-Card-Printer#33]
Dear Sir/Madam,

Using Internet Explorer 11 in combination with your wonderful free product gives an error.

```
◦Exception: Object doesn't support property or method 'startsWith'
◦Resource: http://jira.locamation.lan/s/e7614d0339edcdfe2715997cfc3b53af-CDN/en_GB6rkjka/71011/7a3ba503990e525c1cd68edbfe2e05eb/47dd929b481b68eee9cdb16683a07d8c/_/download/contextbatch/js/greenhopper-rapid-non-gadget,atl.general,gh-rapid,jira.global,jira.project.sidebar,jira.general,-_super/batch.js?agile_global_admin_condition=true&is-server-instance=true&is-system-admin=true&jag=true&jaguser=true&locale=en-GB&nps-not-opted-out=true&sd_licensed=true
◦Line: 2481
◦Column: 605
```

The JIRA error looks like this:
https://i.sli.mg/hpOyfU.png

Firefox, Chrome, and Opera work fine though.

**Comment by qoomon** [comment]
Thx for reporting.
unfortunately i'm running on osx therefore its difficult tu test an ie.
However i will try to fix it

**Comment by qoomon** [comment]
I just add String.prototype.startsWith
But i never tested ie so far so it may not the only issue
may you can test it again?

**Comment by Refalm** [comment]
Hi qoomon,

The Atlassian Marketplace version is from April 2016. Where can I find the latest version to test?

**Comment by rpelaez** [comment]
Hi Refalm,

The Marketplace JIRA addon it's only a link to the github code of qoomon. No upgrade is needed :)

**Comment by Refalm** [comment]
Ah okay. I'm still getting the same error.

**Comment by rpelaez** [comment]
Sorry, the problem was in the plugin. Internet Explorer don't supports StartWith in String object.
http://stackoverflow.com/questions/30867172/code-not-running-in-ie-11-works-fine-in-chrome

Try to download the new version of today from the Marketplace
Thanks!

**Comment by rpelaez** [comment]
Let me know if it works fine!

**Comment by rpelaez** [comment]
A new error is raised in IExplorer 11 when I push the button to print:
- bookmarklet.js line 48 column 23 .... seems to need a ";" character

**Comment by Refalm** [comment]
I've updated the plugin. My experience is different though, hitting the "Print Selected Cards!" button doesn't do anything.

**Comment by qoomon** [comment]
Any errors on console?

On Tue, 5 Jul 2016, 09:27 Refalm, <notifications@github.com> wrote:

> I've updated the plugin. My experience is different though, hitting the
> "Print Selected Cards!" button doesn't do anything.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/qoomon/Jira-Issue-Card-Printer/issues/33#issuecomment-230405758>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADx6AgVfnVAkU_RgcJCkL18-aau9zqPDks5qSgd1gaJpZM4IsTci>
> .
>
-- 

Send from Mobile
