### ISSUE TITLE
Print all cards from one lane in Trello

### ISSUE THREAD

**Issue by derBaSche** [qoomon/Jira-Issue-Card-Printer#34]
Hi everybody,

is it possible to print more than one Trello-Card e.g. all cards in a particular list?
I couldn't find the possibility to select more than one card in Trello, so i'd better ask.

Thanks in advance,
BaSche

**Comment by qoomon** [comment]
Now it is possible  dac931e. Just select the columns you like to print by clicking on the title.

**Comment by qoomon** [comment]
unfortunately  my implementation only works on boards you can't edit :-(

**Comment by qoomon** [comment]
The problem is to know which cards are selected, however i've not found any mark within the html to determine any selection except a single card.
May you have any ideas.

**Comment by qoomon** [comment]
okay it's kinda hacky but it works.
* on read-only you have to select the columns by click on the title so the get highlighted
* on boards you can write you have to select a column by open the add new card input for spesific column
then just run the card printer as usual

**Comment by derBaSche** [comment]
indeed, it is hacky :D ... But it works for now ;). Hence Trello doesn't support multiselection it seems to be hard to find a better solution.

One idea would be to print a single card if it is in detail view and print all cards from the lane if one of them is selected... but that would change the behaviour :/.

Anyway, thanks for fast solution.

**Comment by derBaSche** [comment]
The difference is in the class attribute:

<div class="list-card js-member-droppable ui-droppable _**active-card**_">

The class active-card is added, if selected with arrow-keys.

**Comment by qoomon** [comment]
if you like, i'll implement this aswell

**Comment by derBaSche** [comment]
I'm fine with the current version, because I can do everything I need... I just wanted to contribute something even though it is only some little information ;)
