### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rpelaez** [qoomon/Jira-Issue-Card-Printer#35]
Hi Bengt, How are you? I hope you fine!

Recently someone called M. Piper write us a review of the plugin requesting two new features.
The features are: print from backlog (of Scrum or Kanban boards of JIRA). This is possible?
Another feature is the possibility of print the "Labels" field (standard of JIRA).

Many thanks & best regards!

**Comment by derBaSche** [comment]
Hi everybody,

printing the Backlog from Jira is already working. If it is a lane on a board mark all of them or search all tickets of a project for the "backlog"-status which is usually 'new' or 'selected for development' and print (as described in the readme.file).

The label-issue is not implemented at the moment afaik.

Cheers,
BaSche

**Comment by rpelaez** [comment]
OK Thanks! Then I can implement in the JIRA addon (the print from backlog).
Best,

**Comment by qoomon** [comment]
I am currently on vacation in Italy I will work on the label issue at the end of next week.so long
