### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by ePex** [qoomon/Jira-Issue-Card-Printer#37]
Sometimes I get this error:

{
  "stack": "TypeError: Cannot read property 'toUpperCase' of undefined\n    at data.assignee.split.map.namePart (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:352:78)\n    at Array.map (native)\n    at fillCard (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:352:51)\n    at https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:254:9",
  "message": "Cannot read property 'toUpperCase' of undefined"
}

It looks like it is related to the assigned user. But this user has not any special characters in his name.

**Comment by ePex** [comment]
Ok i got the problem. The assignee had a space after his last name so the split by space went bad. I will make a fork of you repo and send you a pull request

**Comment by qoomon** [comment]
Thx
