### ISSUE TITLE
We're using JIRA agile, want to print sub tasks across multi stories and different status into one paper.

### ISSUE THREAD

**Issue by JasonYanPKI** [qoomon/Jira-Issue-Card-Printer#39]
it seems in the board, pressing shift key doesn't allow you to select across statues columns.

**Comment by qoomon** [comment]
Thats quiet easy. Just search for your issues you like to print within the issue navigator, then call the bookmarklet

**Comment by JasonYanPKI** [comment]
nice, I didn't know that you don't have to select the search result, the bookmark can detect them automatically.
