### ISSUE TITLE
Add components as Label

### ISSUE THREAD

**Issue by qoomon** [qoomon/Jira-Issue-Card-Printer#40]
Add components as Label

**Comment by vladNica** [comment]
Would you appreciate some help with this? My team is in need of this feature and I would like to jump in and help with it.

**Comment by qoomon** [comment]
that would be nice

**Comment by qoomon** [comment]
have a look at https://github.com/qoomon/Jira-Issue-Card-Printer/blob/64e12ddda7d90b4f6e981f0d40c64df5d33a955d/app/lib/jira-issue-tracker.js#L136

**Comment by qoomon** [comment]
it's done. They will be displayed as labels

**Comment by qoomon** [comment]
does this fits your needs or do you need a dedicated checkbox for this

**Comment by vladNica** [comment]
Awesome! Thanks a lot! Works like a charm.

**Comment by qoomon** [comment]
Glad to hear that.
