### ISSUE TITLE
Something changed? 

### ISSUE THREAD

**Issue by ePex** [qoomon/Jira-Issue-Card-Printer#42]
Hello my friend, 

it looks like you changed something? If I use the bookmarklet i normally print some issue with 1 by 2 page grid settings (for our normal sprint board) and then the same issues in a 3 by 6 grid (for a smaller board). 
So if I use the normal bookmarklet it seems that it doesn't scale properly anymore. The icons and fonts are way to large so you can't ready anything. 
If I use the code from the bookmarklet of my fork everything scales pretty well (as I expected) so it seems like you changed something? Maybe within implementing the IE support? 

I am using Chrome Version 54.0.2840.98 (64-bit)

If you need I could make some Screenshots and attach them after I greyed out all the "non public" stuff so I try to avoid this at the moment ^^

Greetings

**Comment by qoomon** [comment]
damn it my bad. Give me a second.

**Comment by qoomon** [comment]
Try again please

**Comment by ePex** [comment]
looks pretty good now (again) ;)
Thanks for the fast fix
