### ISSUE TITLE
"stack": ReferenceError: formatDate is not defined 

### ISSUE THREAD

**Issue by alblitzXIII** [qoomon/Jira-Issue-Card-Printer#46]
# Summary
When trying to print an issue, an error pops up (see screenshot), and it is impossible to print the issue correctly (no description or summary on the card).

# System info
**JIRA-version:** 6.4.7
**Browser:** Google Chrome (Version 54.0.2840.99 m (64-bit))
**Jira-Issue-Card-Printer version:** 1.1.6

# Details
![jiracardprinter_bugreport_screenshot](https://cloud.githubusercontent.com/assets/17527982/21175455/b12b5cd0-c1e2-11e6-931a-80d40800cddb.png)

**Comment by alblitzXIII** [comment]
ok.. it seems the problem is solved. And I didn't do anything on my side. Anyone has an ideas what that could be ?

**Comment by qoomon** [comment]
i did some refactoring.
sorry my bad
