### ISSUE TITLE
Jira without jQuery or jQuery in save mode

### ISSUE THREAD

**Issue by wesflo** [qoomon/Jira-Issue-Card-Printer#47]
Just preload jQuery with this:
javascript:(function(){var head=document.getElementsByTagName('head')[0],jq=document.createElement('script');jq.onload=function(){var script=document.createElement('script');script.src='https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js';head.appendChild(script);head.removeChild(script);};jq.src='https://code.jquery.com/jquery-2.2.4.min.js';head.appendChild(jq);})();

**unminified:**
javascript:(function () {
    var head = document.getElementsByTagName('head')[0],
        jq = document.createElement('script');
    jq.onload = function () {
        var script = document.createElement('script');
        script.src = 'https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js';
        head.appendChild(script);
        head.removeChild(script);
    };
    jq.src = 'https://code.jquery.com/jquery-2.2.4.min.js';
    head.appendChild(jq);
})();

It should be just a temporary workaround!

**Comment by qoomon** [comment]
Did jira drop jquery usage?

**Comment by wesflo** [comment]
I don't know if Atlassian do this, but in our installation it "$" was not available...

**Comment by wesflo** [comment]
this checks if jquery is available... 

javascript:(function () {var a = document.getElementsByTagName("head")[0],b = function () {var d = document.createElement("script");d.src = "https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js", a.appendChild(d), a.removeChild(d)};if ("undefined" == typeof $ || "undefined" == typeof jQuery) {var c = document.createElement("script");c.onload = b, c.src = "https://code.jquery.com/jquery-2.2.4.min.js", a.appendChild(c)} else b()})();

javascript:(function () {
    var head = document.getElementsByTagName('head')[0];
    var loadCardPrinter = function () {
        var script = document.createElement('script');
        script.src = 'https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js';
        head.appendChild(script);
        head.removeChild(script);
    };
    if(typeof $ === 'undefined' || typeof jQuery === 'undefined'){
        var jq = document.createElement('script');
        jq.onload = loadCardPrinter;
        jq.src = 'https://code.jquery.com/jquery-2.2.4.min.js';
        head.appendChild(jq);
    } else {
        loadCardPrinter();
    }
})();

should also work, but i cant test it at the moment...

**Comment by qoomon** [comment]
i just include jquery directly into the bookmarkelt, so i really know what version i'm going to use
