### ISSUE TITLE
404 Not Found exception

### ISSUE THREAD

**Issue by Yolgie** [qoomon/Jira-Issue-Card-Printer#48]
Using the Bookmark:
```
javascript:(function(){ var script = document.createElement("script"); script.src = "https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js"; document.body.appendChild(script); document.body.removeChild(script);})();
```

On Chrome 55.0.2883.87 m or Firefox 50.1.0 results in the following 404:
```
{
  "readyState": 4,
  "responseText": "{\"message\":\"null for uri: https://OURDOMAIN/rest/agile/1.0/issue/ABC-7000?expand=renderedFields,names\",\"status-code\":404}",
  "responseJSON": {
    "message": "null for uri: https://OURDOMAIN/rest/agile/1.0/issue/ABC-7000?expand=renderedFields,names",
    "status-code": 404
  },
  "status": 404,
  "statusText": "Not Found"
}
```

Printing worked perfect previously and no changes were made that the devs are aware of ;)
Thanks for looking into this!

**Comment by qoomon** [comment]
sure.
pls try to reach following endpoints
https://YOUR_DOMAIN/rest/agile/1.0/issue/EXISTING_ISSUE_KEY
https://YOUR_DOMAIN/rest/api/2/issue/EXISTING_ISSUE_KEY

maybe the rest/agile api is not available in all jira versions or it can be disabled?

**Comment by qoomon** [comment]
should work again. i will now try the agile api first then the classic api.

**Comment by Yolgie** [comment]
confirmed working, sorry for the late reply...
