### ISSUE TITLE
Support for Bitbucket

### ISSUE THREAD

**Issue by fabianwilflingsederxxxl** [qoomon/Jira-Issue-Card-Printer#50]
Are you going to support issues from bitbucket ?

**Comment by qoomon** [comment]
Sure, if you can provide me an api documentation and a public access an some board where i can test.

**Comment by Hauptquartier** [comment]
https://confluence.atlassian.com/bitbucket/use-the-bitbucket-cloud-rest-apis-222724129.html

I will send you a board over email

**Comment by qoomon** [comment]
should work :-)

**Comment by qoomon** [comment]
Should also work with private issue lists now.
the documentation make use of api.bitbucket.org/... therefore now cookies are available for authentication. Undocumented but also working bitbucket.org/api/... . Now cookies from current session send and access to private lists is working.

Furthermore it supports List Issue View (print 25 Issues at once)
