### ISSUE TITLE
Show Epic Name instead of Epic issue key

### ISSUE THREAD

**Issue by mhantsch** [qoomon/Jira-Issue-Card-Printer#53]
As a product owner
I want to see the Epic Name on the printed cards instead of the Epic issue key
So that I get a readable wording (similar to a label) on the card instead of an incomprehensible number

**Comment by qoomon** [comment]
should be fixed for now; for up-to-date jira version that support agile api 1.0
if you need a fix for old jira version just let me know

**Comment by mhantsch** [comment]
We're on JIRA v6.4.12 currently (and the Epic names don't seem to work with this version), but we expect to upgrade to v7.3 in the next weeks. I'll wait and check again with the newer version. Thanks for the quick response.

**Comment by qoomon** [comment]
I will try to get the epic name through the old api at this weekend
