### ISSUE TITLE
Show Remaining time for Sub-tasks in Jira when Estimate mark is set

### ISSUE THREAD

**Issue by ilyalavrinov** [qoomon/Jira-Issue-Card-Printer#54]
During planning we set Remaining time in subtasks during planning.
It would be great if Remaining time was shown on the printed cards for subtasks as well as Story Points for stories.

**Comment by admiral-larimda** [comment]
![sprintcards](https://user-images.githubusercontent.com/6028868/28262299-38175d8c-6aeb-11e7-9b69-f9dd26c4e80f.png)
