### ISSUE TITLE
Trello - card should be printed with rendered description

### ISSUE THREAD

**Issue by szoper** [qoomon/Jira-Issue-Card-Printer#57]
Trello supports Markdown in card's description. Unfortunately, card's print preview shows that it would be rendered as-is instead of being parsed and rendered.
What can be done about it? :)

How it looks like in Trello:
![trello - content](https://user-images.githubusercontent.com/2564066/35137923-29045802-fcec-11e7-96ec-b38513ba1909.png)

How it's about to be printed:
![trello - print view](https://user-images.githubusercontent.com/2564066/35137924-2bc6a392-fcec-11e7-85b9-b64f9da5a843.jpg)

**Comment by szoper** [comment]
Ok, an update.

I see that Trello returns raw Markdown only, but I found another Trello printing plugin which uses `marked` for Markdown rendering. You could make use of it as well!
https://github.com/chjj/marked

**Comment by qoomon** [comment]
Thank you, I will implement I it within this week.

**Comment by qoomon** [comment]
done within release 5.3.0

**Comment by szoper** [comment]
Works great! Thank you.

**Comment by qoomon** [comment]
glad to hear that
