### ISSUE TITLE
No working: chrome detect qoomon.github.io as a phishing website

### ISSUE THREAD

**Issue by lozanojardi** [qoomon/Jira-Issue-Card-Printer#58]
Chrome is detecting anything related to qoomon.github.io as a phishing website.

Can you please check it?

**Comment by qoomon** [comment]
I will

**Comment by qoomon** [comment]
thank you so much for reporting this. problem was that I hosted https://qoomon.github.io/otp-authenticator-webapp/ as 'Google Authenticator' including its icon therefore google detect the whole domain qoomon.github.com as scam. I removed all google related branding. So would be great if you can report a false positive to google as well as i already did https://safebrowsing.google.com/safebrowsing/report_error/?hl=en-GB . thank you in advance.

**Comment by qoomon** [comment]
the warning is removed
