### ISSUE TITLE
Support for Kanboard

### ISSUE THREAD

**Issue by fabianwilflingseder** [qoomon/Jira-Issue-Card-Printer#59]
Kanboard is a lightweight and recent project management web software.
The number of the users of Kanboard is rising continiously.

So my question is if you are going to provide support for Kanboard?

https://kanboard.org/

If required, i can offer a testing instance of Kanboard, because it is self-hosted!

Best wishes

**Comment by qoomon** [comment]
hi,
I can have a look if you provide me an instance.

**Comment by qoomon** [comment]
Can you check which if the following fields are applicable to kanboard?
issueData.type
issueData.summary 
issueData.description
issueData.labels 
issueData.assignee
issueData.avatarUrl 
issueData.dueDate
issueData.hasAttachment

**Comment by fabianwilflingseder** [comment]
Hi

Here is a small test instance of kanboard: https://daslager.000webhostapp.com
Username and Password are admin

There is an api, but i am not sure if you can work with it: https://github.com/kanboard/kanboard/blob/master/doc/en_US/api-json-rpc.markdown

Fields:
* For issueData.type the category can be used, but it is not sure if every task in canboard has a category
* issueData.summary is the task title
* issueData.description is the default description of the task
* issueData.labels are the task-tags
* issueData.assignee is the task-board-assignee
* issueData.avatarUrl is available, if the user uploaded a profile image, otherwise a icon is generated
* issueData.dueDate is available
* issueData.hasAttachment is available

**Comment by qoomon** [comment]
Okay i will see what i can do. I think I will have some spare time this weekend

**Comment by qoomon** [comment]
is it possible to to select multiple task, somehow?

**Comment by fabianwilflingseder** [comment]
Maybe in the board view?

Dashboard -> Link to project -> Board

![2018-03-09_17h45_53](https://user-images.githubusercontent.com/27973610/37218764-c0c9a588-23c1-11e8-8fd4-214c6be59570.png)

**Comment by qoomon** [comment]
should work with version 5.4.0

**Comment by qoomon** [comment]
I got following error

> VM5466:1 Refused to load the script 'https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
