### ISSUE TITLE
Using this with Firefox

### ISSUE THREAD

**Issue by TumTum23** [qoomon/Jira-Issue-Card-Printer#82]
Hey there Bengt!

I am working under MrAddon currently and we are having a small issue with using this on Firefox,

Our issue cards will not show next to each other (have attached photos of this working in chrome but not in firefox)

Do you have any idea how we could fix this please, I think it is an issue with the CSS but am not quite sure,

Regards,
Joseph.

<img width="998" alt="Screen Shot 2019-03-13 at 17 46 06" src="https://user-images.githubusercontent.com/33499460/54297947-23e4b180-45b8-11e9-8d20-f5b43e5dac90.png">
<img width="1002" alt="Screen Shot 2019-03-13 at 17 46 10" src="https://user-images.githubusercontent.com/33499460/54297948-23e4b180-45b8-11e9-8ea1-06b2a4808459.png">

**Comment by TumTum23** [comment]
I think it is to do with this code:

    // enable/disable single card page
    $(".card", printFrame.document).css({ 'page-break-after' : '', 'float' : '', 'margin-bottom': '10px' });
    if (settings.singleCardPage) {
      //alert('hola')
      $(".card", printFrame.document).css({ 'page-break-after': 'always', 'float': 'none', 'margin-bottom': '10px' });
      //alert('adios')
    } else {
      $(".card", printFrame.document).each(function(index, element){
         if(index % (settings.colCount * settings.rowCount ) >= (settings.colCount * (settings.rowCount - 1))){
         $(element).css({ 'margin-bottom': '10px' });
         }
      });
    }
  }

**Comment by qoomon** [comment]
I will have a look at it at the weekend.Seems to be a known bug https://www.fxsitecompat.com/en-CA/docs/2017/page-break-before-after-in-print-stylesheet-may-lead-to-lack-or-overlap-of-elements/

**Comment by qoomon** [comment]
any ideas?

**Comment by rpelaez** [comment]
Hi Bengt, I'm in charge of this, but I have no idea how to solve the issue with firefox 
1 page x page works perfect, but the rest fails... 
I need to try with your last version if the issue still happens.

**Comment by rpelaez** [comment]
Checked with the new version, when you change the grid dimensions the layout goes to the infinite.
With 1cardxpage works, the rest fails
![Captura de pantalla 2019-06-16 a las 20 10 57](https://user-images.githubusercontent.com/1374732/59567815-0ae61380-9073-11e9-85f9-fcc2b1cf913c.png)
Thanks Bengt!

**Comment by qoomon** [comment]
Should work now, problem was that firefox does not set iframe body height to "100%" by default as chrome does.
I also add 'color-adjust: exact' to enforce background color and images to be printed, without the need of checking the specific option in print menu.

**Comment by qoomon** [comment]
please confirm fix
