### ISSUE TITLE
May we host this on our intranet for our own in-house use?

### ISSUE THREAD

**Issue by ricksbrown** [qoomon/Jira-Issue-Card-Printer#86]
@qoomon Thanks for the bookmarklet, we are considering using it on my team.

Regarding this requirement 

> You are not allowed to change or host this bookmarklet on your own.

We would like to host it behind our corporate firewall, on our private network, purely for our own use, just a handful of people for now, it would be completely inaccessible from the internet.

Because our environment is quite secure, this allows us to eyeball the script before using it, and gives us control over when it is updated.

Would this be acceptable to you and your licence conditions?

**Comment by qoomon** [comment]
As long as you don't modify the code and keep my watermark i would be fine if you like to have fixes just let me know.

**Comment by ricksbrown** [comment]
@qoomon thanks for that much appreciated 😄
